name: Ruby Job Engine

on:
  schedule:
    - cron: "0 14 * * *"  # once per day (UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run script
        run: python main.py
